### ISSUE TITLE
Improving README

### ISSUE THREAD

**Issue by henriquecrang** [yanshinayder/OnthisDay#1]
The README file says "start the script", but it is not clear to me. The rep has many different scripts. Which one I should run and with which interpreter?

**Comment by yanshinayder** [comment]
You must run the script through a Python interpreter, if you want, you can, through the collect_events.py file, generate a new events.json file.
If not necessary, create virtualenv, activate it, install the modules and run through the terminal.
I will add this information to the README so that it is better understood.

**Comment by henriquecrang** [comment]
Great! Any version of Python will do the trick?

**Comment by yanshinayder** [comment]
Yes, all python 3 versions will do the trick, but with your differences. I recommend version 3.9, which was used.

**Comment by henriquecrang** [comment]
This information should be presented in the README. Btw, when you feel like the README is good enough for a first version you can close this issue.

**Comment by yanshinayder** [comment]
Ok, Thanks for a lot.
